# https://github.com/janosh/awesome-sveltekit/blob/main/site/.eslintrc.yml
env:
  browser: true
  node: true
extends:
  - prettier
  - plugin:svelte/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files: ["*.svelte"]
    parser: svelte-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
rules:
  no-inner-declarations: off
  "@typescript-eslint/ban-ts-comment": off
ignorePatterns: [build/, dist/]
