request: ["get_preferences"]
response:
  message: >
    {
      "animations_on": null,
      "unceasing_animations": null,
      "animation_speed": null,
      "sound_on": false,
      "volume": null
    }
