/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function greet(name: string) {
    return invoke()<string>("greet", { name })
}

export function getApiKeys() {
    return invoke()<ApiKeys>("get_api_keys")
}

export function playSound(sound: Sound, volume: number) {
    return invoke()<null>("play_sound", { sound,volume })
}

export function getPreferences() {
    return invoke()<Preferences>("get_preferences")
}

export function setPreferences(preferences: Preferences) {
    return invoke()<null>("set_preferences", { preferences })
}

export type ApiKey = { value: string; source: Source }
export type Preferences = { animations_on: boolean | null; unceasing_animations: boolean | null; animation_speed: number | null; sound_on: boolean | null; volume: number | null }
export type Source = "Environment"
export type Sound = "Switch" | "Whoosh"
export type ApiKeys = { openai: ApiKey | null }
