/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function greet(name: string) {
    return invoke()<string>("greet", { name })
}

export function getApiKeys() {
    return invoke()<ApiKeys>("get_api_keys")
}

export function setApiKey(filename: string | null, service: Service, apiKey: string) {
    return invoke()<null>("set_api_key", { filename,service,apiKey })
}

export function playSound(sound: Sound, volume: number, speed: number) {
    return invoke()<null>("play_sound", { sound,volume,speed })
}

export function getPreferences() {
    return invoke()<Preferences>("get_preferences")
}

export function setPreferences(preferences: Preferences) {
    return invoke()<null>("set_preferences", { preferences })
}

export function getSystemInfo() {
    return invoke()<SystemInfo>("get_system_info")
}

export function chat() {
    return invoke()<null>("chat")
}

export type ApiKeys = { openai: string | null }
export type Preferences = { animations_on: boolean | null; unceasing_animations: boolean | null; animation_speed: number | null; sound_on: boolean | null; volume: number | null }
export type Service = "OpenAI"
export type OS = "MacOS" | "Linux"
export type Shell = "Bash" | "Zsh"
export type SystemInfo = { zamm_version: string; os: OS | null; shell: Shell | null; shell_init_file: string | null }
export type Sound = "Switch" | "Whoosh"
