/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function greet(name: string) {
    return invoke()<string>("greet", { name })
}

export function getApiKeys() {
    return invoke()<ApiKeys>("get_api_keys")
}

export function playSound(sound: Sound) {
    return invoke()<null>("play_sound", { sound })
}

export type ApiKey = { value: string; source: Source }
export type Source = "Environment"
export type Sound = "Switch"
export type ApiKeys = { openai: ApiKey | null }
