name: rust

on:
  pull_request:
  push:
    branches: [main]

env:
  POETRY_VERSION: "1.5.1"
  PYTHON_VERSION: "3.11.4"
  NODEJS_VERSION: "20.5.1"
  RUST_VERSION: "1.71.1"
  PRE_COMMIT_VERSION: "3.3.3"

jobs:
  rust:
    name: Run Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        continue-on-error: false
        with:
          workspaces: "src-tauri -> target"
      - name: Install poetry
        run: |
          pipx install poetry==$POETRY_VERSION
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Install dependencies
        run: |
          cd src-python && poetry install
      - name: Setup Python sidecar
        run: |
          cd src-python && poetry run make
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - name: Build Svelte
        run: make
        working-directory: src-svelte
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
      - name: Run Rust Tests
        run: |
          cd src-tauri && cargo test
